# Generated by Django 3.1.2 on 2020-10-22 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dane',
            name='kwota',
        ),
        migrations.RemoveField(
            model_name='dane',
            name='kwota_slownie',
        ),
        migrations.RemoveField(
            model_name='dane',
            name='miesiac',
        ),
        migrations.RemoveField(
            model_name='dane',
            name='pododdzial',
        ),
    ]
