# Generated by Django 3.1.2 on 2020-10-22 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0002_auto_20201022_2244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dane',
            name='adres',
        ),
    ]
