# Generated by Django 3.1.2 on 2020-10-27 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0003_remove_dane_adres'),
    ]

    operations = [
        migrations.AddField(
            model_name='dane',
            name='typ',
            field=models.CharField(default='pj', max_length=30),
            preserve_default=False,
        ),
    ]
