# Generated by Django 3.1.2 on 2020-10-28 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0006_dane_miesiac'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dane',
            name='miesiac',
            field=models.CharField(default='---', max_length=30),
        ),
    ]
