# Generated by Django 3.1.2 on 2020-10-29 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0007_auto_20201028_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='dane',
            name='stopien_id',
            field=models.CharField(default='1', max_length=10),
            preserve_default=False,
        ),
    ]
