# Generated by Django 3.1.2 on 2020-10-30 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0008_dane_stopien_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='dane',
            name='nr_rozkazu',
            field=models.CharField(default='99', max_length=10),
            preserve_default=False,
        ),
    ]
