# Generated by Django 3.1.2 on 2020-11-04 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0009_dane_nr_rozkazu'),
    ]

    operations = [
        migrations.AddField(
            model_name='dane',
            name='doniesione',
            field=models.CharField(default='X', max_length=1),
            preserve_default=False,
        ),
    ]
