# Generated by Django 3.1.2 on 2020-11-04 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0010_dane_doniesione'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dane',
            name='doniesione',
            field=models.CharField(default='', max_length=1),
        ),
    ]
