# Generated by Django 3.1.2 on 2021-04-26 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0011_auto_20201104_1803'),
    ]

    operations = [
        migrations.CreateModel(
            name='RightsSupport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('user_rights', 'Globalne uprawnienia użytkownika'),),
                'managed': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Dane_osobowe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=30)),
                ('nazwisko', models.CharField(max_length=30)),
                ('stopien', models.CharField(max_length=30)),
                ('pluton', models.CharField(max_length=1)),
                ('wydzial', models.CharField(max_length=5)),
                ('grupa', models.CharField(max_length=10)),
            ],
        ),
    ]
