# Generated by Django 3.1.2 on 2021-05-25 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0014_auto_20210525_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='adres',
            field=models.CharField(default='', max_length=100),
        ),
    ]
