# Generated by Django 3.1.2 on 2021-12-09 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0015_userprofile_adres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dane',
            name='doniesione',
            field=models.CharField(blank=True, default='', max_length=1),
        ),
        migrations.AlterField(
            model_name='dane',
            name='transport',
            field=models.CharField(max_length=50),
        ),
    ]
