# Generated by Django 3.1.2 on 2021-12-09 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0016_auto_20211209_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dane',
            name='nr_rozkazu',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
